// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAke8uJm1rROM4plDDFpE0PDdtdnWtINMI',
    appId: '1:500536340950:android:5f19a44ca20a1357a7f477',
    messagingSenderId: '500536340950',
    projectId: 'project-notifications-29a71',
    storageBucket: 'project-notifications-29a71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtg_jg4Bwr3Q1IP8eXqXSPtfMNfOlHKcw',
    appId: '1:500536340950:ios:cf0f07f7fa0ee40ba7f477',
    messagingSenderId: '500536340950',
    projectId: 'project-notifications-29a71',
    storageBucket: 'project-notifications-29a71.firebasestorage.app',
    iosBundleId: 'com.example.projectNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxJ509b0UPTZ04noL305RGwbRgpi8BFio',
    appId: '1:500536340950:web:68325a1df2dcef18a7f477',
    messagingSenderId: '500536340950',
    projectId: 'project-notifications-29a71',
    authDomain: 'project-notifications-29a71.firebaseapp.com',
    storageBucket: 'project-notifications-29a71.firebasestorage.app',
    measurementId: 'G-QHXYQW6B5G',
  );
}
